language: python
python:
  - "2.6"
  - "2.7"
install:
  - "make --quiet install"
script:
  - "make --quiet travis"
env:
  - DJANGO=1.4.2
  - DJANGO=1.4.3
  - DJANGO=1.4.4
  - DJANGO=1.4.5
  - DJANGO=1.5
  - DJANGO=1.5.1
matrix:
  include:
    - python: 3.2
      env: DJANGO=1.5
    - python: 3.2
      env: DJANGO=1.5.1
    - python: 3.3
      env: DJANGO=1.5
    - python: 3.3
      env: DJANGO=1.5.1
